### ISSUE TITLE
Parse reply count for a Post

### ISSUE THREAD

**Issue by CodedOre** [CodedOre/NewCaw#15]
As the Twitter v1 API does not return a count for replies, we need to calculate this from the attached replies.

A topic for when replies are actually fetched though.

**Comment by IBBoard** [comment]
Do we need to have reply counts? Maybe we just set it to -1 and toggle that part of the UI depending on whether it's non-negative. Because the best you're going to get from Twitter v1 is "we fetched up to N replies and there may or may not be more". If we request 50 and get 50 then we don't know if that's because there were 50 replies and we got them all or because there were over 50 and we just got the (latest?) 50, so you can't even show "over 50 replies".

**Comment by CodedOre** [comment]
Makes sense.

Made the change to this in 16b1e25.
