### ISSUE TITLE
Better way to parse Mastodon links

### ISSUE THREAD

**Issue by CodedOre** [CodedOre/NewCaw#37]
Mastodon doesn't provide us with an simple text that is extended with an `entities`-Array containing special entities.
Instead, it provides an fully-formatted HTML-block. While this might be great for websites, it is not so great for us as we need to parse out the links leading to mentions, links or tags and replace them with our own.

As of now, we do it with an "simple" [regular](https://github.com/CodedOre/NewCaw/blob/4f81f8b2fb7b0f788bcb660598e5bab69be3d76c/lib/Mastodon/Utils/TextUtils.vala#L61-L73) [expression](https://github.com/CodedOre/NewCaw/blob/4f81f8b2fb7b0f788bcb660598e5bab69be3d76c/lib/Mastodon/Utils/ParseUtils.vala#L66-L78), which does work... mostly.

If the server does not provide the parameters like we expect, it results in it failing to get the link, which is places as is in the Label which then complains about parameters it don't recognize.

So, we need to find a solution which does not care about the "right" order to detect the links and replace them with ones we can work with.

**Comment by IBBoard** [comment]
Insert obligatory [StackOverflow HTML and regex link](https://stackoverflow.com/questions/1732348/regex-match-open-tags-except-xhtml-self-contained-tags/1732454#1732454)

Hopefully Mastodon is one of the cases where it's consistent and reliable 🙂

However, it might be safer to use a HTML parsing library. You'd then be able to put in logic for "if it has this attribute then handle it as a link/hashtag/etc" and "if it isn't one of those then only copy over the tags and attributes that Pango supports". The only drawback *might* be that it's slower (because it needs to build the DOM). But if the alternative is that messages refuse to show because the tags don't comply with Pango's limited subset then it might be an option.

Is there an example of where it doesn't do it right?

**Comment by CodedOre** [comment]
> Is there an example of where it doesn't do it right?

Just had the case yesterday. Apparently Mastodon recently switched the `target` and `rel` attributes in their replies, which resulted in it not working properly.

An XML-Parser might be the better idea. Rest seems to provide one, so let's see if we can use that maybe.
