### ISSUE TITLE
Bugs when displaying text from certain tweets

### ISSUE THREAD

**Issue by CodedOre** [CodedOre/NewCaw#50]
When displaying certain tweets from Twitter, the text is not properly displayed.

This can happen in two ways. First, mentions, links, etc. are positioned wrong and therefore some text is cut off. Secondly, the text is not displayed at all since GTK finds invalid UTF characters and therefore displays nothing.

I have yet to seen this with Mastodon posts, and all posts that have this issue use some emojis, so I guess the issue is related to emojis as well.

A good test case for this are the tweets from [**@TwitterDev**](https://twitter.com/TwitterDev).

**Comment by IBBoard** [comment]
GTK/Pango is slightly unhelpful in that it tends to just not show anything in these situations.

From what I remember of dealing with this in Cawbird (which does it in C!), you're not doing something like indexing by byte instead of unicode character, are you? Because that would cause it to mangle non-ASCII characters like emoji. I've had to use `g_utf8_next_char()` at times ([src](https://github.com/IBBoard/cawbird/blob/master/src/CbTextTransform.c#L137)).

**Comment by CodedOre** [comment]
> From what I remember of dealing with this in Cawbird (which does it in C!), you're not doing something like indexing by byte instead of unicode character, are you?

Looking at my code, I probably do... Right now I just slice the string..
Guess that explains the first issue. Means I need to switch that out with an method that uses `g_utf8_next_char()`.

That leaves the second one. GTK does print out the text in the terminal, so I can see that the emojis are the issue.
For example, the ⬇️ icon from [this tweet](https://twitter.com/TwitterDev/status/1567271425899110401) is given to `\xe2`, which is read as wrong...

**Comment by CodedOre** [comment]
Turns out the solution was relatively simple, as GLib conveniently provides `string.index_of_nth_char` to retrieve the index we need.

Should be resolved now.
