### ISSUE TITLE
What's the future of the Twitter integration?

### ISSUE THREAD

**Issue by mxmvncnt** [CodedOre/NewCaw#70]
So, with the recent API changes regarding 3rd party clients, I was wondering, what's the future of the Twitter part of NewCaw?

**Comment by IBBoard** [comment]
It's dead. Twitter killed it. The developer terms are clear - you can't create a third-party client. Musk wants everyone to suffer adverts and his ridiculous design decisions, or buy Twitter Blue and pay money to _still_ see ads and bad design decisions.

I've already got a pull request in that deleted the Twitter code from NewCaw.

https://github.com/CodedOre/NewCaw/discussions/67

**Comment by CodedOre** [comment]
Well, if the change of the term wouldn't have killed it, the removal of an paid-less access sure would've done it.

Since @IBBoard, PR which included the removal of the platform code was now merged, I will close this issue as "completed".

**Comment by Asday** [comment]
Doesn't strike me as prohibited.

> A. Reverse Engineering and other Restrictions.  You shall not and you shall not attempt to (or allow others to): [...] (c) use or access the Licensed Material [Twitter API and content] to create or attempt to create a substitute or similar service or product to the Twitter Applications;

No idea really what NewCaw is in relation to Cawbird, but if they're similar at all, it's nothing like the existing twitter applications.  It's a purely chronological feed from followed accounts for the desktop, contrasted with the algorithmically sorted feed from followed accounts and suggested tweets for the browser.

My guess is that's why Cawbird continues to work for me.  I was just coming to feature request drag'n'drop for the tweet links and had no idea the project had been archived.

**Comment by IBBoard** [comment]
> No idea really what NewCaw is in relation to Cawbird

NewCaw is a rewrite of Cawbird in pure Vala with a GTK4/Adwaita UI. It was going to support Twitter _and_ Mastodon.

> but if they're similar at all, it's nothing like the existing twitter applications. It's a purely chronological feed from followed accounts for the desktop, contrasted with the algorithmically sorted feed from followed accounts and suggested tweets for the browser.

It is very similar to existing Twitter applications because it lets you view your feed, like the website shows you your feed.

It may not strike you as prohibited, but it strikes Twitter as prohibited. Which is why Twitter disabled the primary Cawbird API keys.

If Cawbird is still working for you then it's because you're using alternate keys (e.g. the Arch keys) and Musk's Twitter is too under-staffed and/or incompetent to have found them and disabled them yet, and because they've not disabled the old APIs and forced everyone to the "$100 PER MONTH for 'hobbyist' access" or higher new API.

Every single announcement by Twitter Dev and the revoking of keys for multiple major Twitter clients has made it blatantly clear that third-party clients are no longer acceptable, and the new API structure makes it clearer still that they're focussing on novelty apps and occasional use rather than anything that looks like clients.
