### ISSUE TITLE
Load video files

### ISSUE THREAD

**Issue by CodedOre** [CodedOre/NewCaw#9]
The idea for providing the videos (and GIF's) to the UI was to store them as a `Gtk.MediaFile`, allowing us to place them anywhere a `Gdk.Paintable` is accepted and use `Gtk.MediaControls`.

However, apart from the fact that Twitter's v2 API still don't include video urls, GTK as of now only can create a `Gtk.MediaFile` from a file. However, creating a `Gtk.MediaFile` from a `InputStream` is [something discussed](https://gitlab.gnome.org/GNOME/gtk/-/issues/4062).

Waiting on this issue to see if there will be progress, or if we need to store a file (probably in `/tmp`) to load that to `Gtk.MediaFile` (or something else entirely).

**Comment by CodedOre** [comment]
Loading videos is now implemented by storing the downloaded `InputStream` into a file and then creating the Paintable from the file. This also allowed me to remove the `gdk-pixbuf` dependency, as we no longer need `Gdk.Pixbuf` to create the `Gdk.Texture`.

However, there is the question of where to store the loaded files. Right now, I've set the directory to `XDG_CACHE_HOME`, similar to how Fractal is doing it. However, this means that the files don't disappear by themselves. We could use this to cache media over multiple sessions, but we dismiss that idea the question is if we better use `/tmp` instead.

**Comment by IBBoard** [comment]
You're assuming that `/tmp/` is cleared between sessions. IIRC Ubuntu mounts it as an in-memory file system, but Redhat-based systems and openSUSE just have it as a regular file system (and often just as a directory on root). You can't assume that files will exist across invocations, but you also can't assume that they won't.

https://tldp.org/LDP/Linux-Filesystem-Hierarchy/html/tmp.html

Given that media can get quite big (compared to caching avatars, which are small and appear again and again) then I'd be inclined to try and have a hook that clears it up. In old Cawbird we could do it on pruning the timeline. Worst case is trying to do it in the background on start and stop of the app (but you'd probably want to find all files and delete rather than tracking the ones for this session, just in case the app crashes).
